### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro-Int-scikit-learn#1]
**Description/Motivation**
After relocating the related wrapper and howto code the following steps are required.

**Task list**
- [x] 1. Setup workflow ci.yml (Detlef)
- [x] 2. Integration RTD (Detlef)
- [x] 3. Integration PyPI (Detlef)
- [ ] 4. Integration Conda (Detlef)
- [x] 5. Completion of RTD
   - [x] Introduction
   - [x] API
   - [x] Howtos 
- [x] 6. Release v0.1.0
- [x] 7. Integration MLPro extension hub (follow steps in auto-generated issue)
